// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/cap/imooc.proto

package go_micro_service_imooc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Cap service

type CapService interface {
	SayHello(ctx context.Context, in *SayReq, opts ...client.CallOption) (*SayResp, error)
}

type capService struct {
	c    client.Client
	name string
}

func NewCapService(name string, c client.Client) CapService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.imooc"
	}
	return &capService{
		c:    c,
		name: name,
	}
}

func (c *capService) SayHello(ctx context.Context, in *SayReq, opts ...client.CallOption) (*SayResp, error) {
	req := c.c.NewRequest(c.name, "Cap.SayHello", in)
	out := new(SayResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cap service

type CapHandler interface {
	SayHello(context.Context, *SayReq, *SayResp) error
}

func RegisterCapHandler(s server.Server, hdlr CapHandler, opts ...server.HandlerOption) error {
	type cap interface {
		SayHello(ctx context.Context, in *SayReq, out *SayResp) error
	}
	type Cap struct {
		cap
	}
	h := &capHandler{hdlr}
	return s.Handle(s.NewHandler(&Cap{h}, opts...))
}

type capHandler struct {
	CapHandler
}

func (h *capHandler) SayHello(ctx context.Context, in *SayReq, out *SayResp) error {
	return h.CapHandler.SayHello(ctx, in, out)
}
